.TH "latex" 3 "Tue Nov 5 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
latex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <latex\&.h>\fP
.PP
Inherited by \fBarray\fP, \fBlist\fP, and \fBtree\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual string \fBgetCadena\fP ()"
.br
.ti -1c
.RI "virtual string \fBgetCadenaTemp\fP ()"
.br
.ti -1c
.RI "\fBlatex\fP (void)"
.br
.ti -1c
.RI "\fB~latex\fP (void)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBcadena\fP"
.br
.ti -1c
.RI "string \fBcadena_temp\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "latex::latex (void)"

.SS "latex::~latex (void)"

.SH "Member Function Documentation"
.PP 
.SS "string latex::getCadena ()\fC [virtual]\fP"

.PP
Reimplemented in \fBarray\fP, and \fBlist\fP\&.
.SS "string latex::getCadenaTemp ()\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "string latex::cadena\fC [protected]\fP"

.SS "string latex::cadena_temp\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
