.TH "list_node" 3 "Mon Oct 7 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list_node\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlist_node\fP (int v, \fBlist_node\fP *)"
.br
.ti -1c
.RI "\fB~list_node\fP ()"
.br
.ti -1c
.RI "void \fBset_value\fP (int)"
.br
.ti -1c
.RI "int \fBget_value\fP ()"
.br
.ti -1c
.RI "void \fBset_next\fP (\fBlist_node\fP *)"
.br
.ti -1c
.RI "\fBlist_node\fP * \fBget_next\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "list_node::list_node (intv, \fBlist_node\fP *nxt = \fCNULL\fP)"

.SS "list_node::~list_node ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBlist_node\fP * list_node::get_next ()"

.SS "int list_node::get_value ()"

.SS "void list_node::set_next (\fBlist_node\fP *new_next)"

.SS "void list_node::set_value (intnew_value)"


.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
