.TH "/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/PROYECTO/list_node.cpp" 3 "Mon Oct 7 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/PROYECTO/list_node.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'list_node\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
