.TH "/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/list.h" 3 "Tue Nov 5 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/list.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'latex\&.h'\fP
.br
\fC#include 'list_node\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlist\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
