.TH "/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/main.cpp" 3 "Mon Oct 7 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'array\&.h'\fP
.br
\fC#include 'list\&.h'\fP
.br
\fC#include 'tree\&.h'\fP
.br
\fC#include 'to_tex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
