.TH "node" 3 "Sat Nov 2 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tree_node\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBkey_value\fP"
.br
.ti -1c
.RI "\fBnode\fP * \fBleft\fP"
.br
.ti -1c
.RI "\fBnode\fP * \fBright\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int node::key_value"

.SS "\fBnode\fP* node::left"

.SS "\fBnode\fP* node::right"


.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
