.TH "page1" 3 "Tue Nov 5 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page1 \- Recommended Lectures 

.SH "Data Structures"
.PP
http://en.wikipedia.org/wiki/Data_structure 
.SH "Graph Theory"
.PP
http://en.wikipedia.org/wiki/Graph_theory 
.SS "Array"
http://en.wikipedia.org/wiki/Array 
.SS "Linked List"
http://en.wikipedia.org/wiki/Linked_list 
.SS "Queue"
http://en.wikipedia.org/wiki/Queue_%28abstract_data_type%29 
.SS "Stack"
http://en.wikipedia.org/wiki/Stack_%28abstract_data_type%29 
.SS "Binary Tree"
http://en.wikipedia.org/wiki/Binary_tree 
