.TH "/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/to_tex.h" 3 "Mon Oct 7 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/to_tex.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcreate_tex\fP (string, string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void create_tex (string, string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
