.TH "/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/to_tex.cpp" 3 "Sat Nov 2 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/to_tex.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'to_tex\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcreate_tex\fP (string file_name, string cadena)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void create_tex (stringfile_name, stringcadena)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
