.TH "tree" 3 "Sat Nov 2 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tree\&.h>\fP
.PP
Inherits \fBlatex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtree\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fB~tree\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "void \fBinsert_root\fP (int key)"
.br
.RI "\fIInserts the root node of the tree, initially its leaves are pointing to NULL\&. \fP"
.ti -1c
.RI "void \fBdestroy_tree\fP ()"
.br
.RI "\fIDestroy each leaf if is not points to NULL\&. \fP"
.ti -1c
.RI "void \fBinsert_child\fP (int key, \fBnode\fP *leaf)"
.br
.RI "\fIInserts a leaf with value 'key' in the node 'leaf'\&. \fP"
.ti -1c
.RI "\fBnode\fP * \fBsearch\fP (int key)"
.br
.RI "\fIReturns the node with the key_value 'key'\&. \fP"
.ti -1c
.RI "void \fBfinish_tree\fP ()"
.br
.RI "\fIDraws the tree on the \&.tex file\&. \fP"
.ti -1c
.RI "\fBnode\fP * \fBreturn_root\fP ()"
.br
.RI "\fIReturns the root of the tree\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tree::tree ()"

.PP
Default constructor\&. 
.SS "tree::~tree ()"

.PP
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void tree::destroy_tree ()"

.PP
Destroy each leaf if is not points to NULL\&. 
.SS "void tree::finish_tree ()"

.PP
Draws the tree on the \&.tex file\&. 
.SS "void tree::insert_child (intkey, \fBnode\fP *leaf)"

.PP
Inserts a leaf with value 'key' in the node 'leaf'\&. 
.SS "void tree::insert_root (intkey)"

.PP
Inserts the root node of the tree, initially its leaves are pointing to NULL\&. 
.SS "\fBnode\fP * tree::return_root ()"

.PP
Returns the root of the tree\&. 
.SS "\fBnode\fP * tree::search (intkey)"

.PP
Returns the node with the key_value 'key'\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
