.TH "tree" 3 "Sat Nov 2 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tree\&.h>\fP
.PP
Inherits \fBlatex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtree\fP ()"
.br
.ti -1c
.RI "\fB~tree\fP ()"
.br
.ti -1c
.RI "void \fBdestroy_tree\fP ()"
.br
.ti -1c
.RI "\fBnode\fP * \fBsearch\fP (int key)"
.br
.ti -1c
.RI "void \fBfinish_tree\fP ()"
.br
.ti -1c
.RI "\fBnode\fP * \fBdevolver\fP ()"
.br
.ti -1c
.RI "void \fBpreTree\fP (\fBnode\fP *)"
.br
.ti -1c
.RI "void \fBinsert\fP (int key, \fBnode\fP *leaf)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tree::tree ()"

.SS "tree::~tree ()"

.SH "Member Function Documentation"
.PP 
.SS "void tree::destroy_tree ()"

.SS "\fBnode\fP * tree::devolver ()"

.SS "void tree::finish_tree ()"

.SS "void tree::insert (intkey, \fBnode\fP *leaf)"

.SS "void tree::preTree (\fBnode\fP *leaf)"

.SS "\fBnode\fP * tree::search (intkey)"


.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
