.TH "/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/tree.cpp" 3 "Sat Nov 2 2013" "Version 1.0" "DataStructures4Beamer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mtorres/Dropbox/Universidad/Estructuras/Proyecto1/FoxHound/src/tree.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tree\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBcontador\fP =0"
.br
.ti -1c
.RI "int \fBcontador2\fP =0"
.br
.ti -1c
.RI "int \fBvariable\fP =0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int contador =0"

.SS "int contador2 =0"

.SS "int variable =0"

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures4Beamer from the source code\&.
